import { useState, useEffect } from 'react';
import type { NextPage } from 'next';
import Head from 'next/head';
import { useWallet } from '../src/hooks/useWallet';
import { ConnectWallet } from '../src/components/buttons/connectWallet';
import { Footer } from '../src/components/footer/footer';
import { useAccount } from '../src/hooks/useAccount';
import { CreateAccountModal } from '../src/components/modals/createAccount';
import { GifLink as GifLinkForm } from '../src/components/forms/gifLink';
import { Button } from '../src/components/buttons/button';

const Home: NextPage = () => {
  const { walletAddress, connectWallet } = useWallet();
  const { notExistingAccount, createGifAccount, gifList } = useAccount(walletAddress);

  const [isModalOpen, setModalOpen] = useState(false);

  useEffect(() => {
    setModalOpen(notExistingAccount);
  }, [notExistingAccount]);

  return (
    <>
      <div>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main className="max-w-7xl mx-auto sm:px-6 lg:px-8">
          <div className="flex justify-center pt-20">
            <div>
              <div className="flex flex-col items-center">
                <p className="text-2xl font-bold my-4">🖼 Awesome GIF Portal</p>
                <p className="sub-text my-4">View your GIF collection in the metaverse ✨</p>
                {!walletAddress && <ConnectWallet onClick={connectWallet} />}

                {walletAddress && (
                  <>
                    {notExistingAccount && <Button onClick={createGifAccount}>Create account</Button>}
                    {!notExistingAccount && (
                      <>
                        <GifLinkForm />
                        <div className="grid grid-cols-3 gap-2 justify-center">
                          {gifList.map((item) => (
                            <div className="flex flex-col justify-self-center self-center" key={item.gifLink}>
                              <img src={item.gifLink} />
                            </div>
                          ))}
                        </div>
                      </>
                    )}
                  </>
                )}
              </div>
            </div>
          </div>
        </main>

        <Footer />
      </div>
      <CreateAccountModal isOpen={isModalOpen} setOpen={setModalOpen} onCreate={createGifAccount} />
    </>
  );
};

export default Home;
